version: '3.7'

services: 
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=be-talent-db
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: